// npm dependencies
import 'angular/angular';
import 'angular-ui-router';
import 'angular-animate/angular-animate';

// The template file is generated by the gulp build
import '../.tmp/templates';

// import anything the app needs
import './config';
import './routes';
